In [133]:
import json
import pickle
import sys
sys.path.append("/mnt/lustre/jkyang/wxpeng/CVPR23/PVSG_Image")

In [134]:
class PVSGAnnotation:
    def __init__(self, anno_file):
        with open(anno_file, "r") as f:
            anno = json.load(f)
            
        self.anno = anno
        videos = {}
        for video_anno in anno:
            videos[video_anno['video_id']] = video_anno
        self.videos = videos


    def __getitem__(self, vid):
        assert vid in self.videos
        return self.videos[vid]

In [135]:
def load_json(filepath):
    with open(filepath, "r") as f:
        return json.load(f)
def load_pickle(filepath):
    with open(filepath, "rb") as f:
        return pickle.load(f)

### Load GT

In [165]:
gt_json = load_json("/mnt/lustre/jkyang/wxpeng/CVPR23/pvsg_data/pvsg_demo.json")
gt = PVSGAnnotation("/mnt/lustre/jkyang/wxpeng/CVPR23/pvsg_data/pvsg_demo.json")

In [166]:
19.0 * 5

95.0

In [167]:
gt_json

[{'video_id': '1001_7007447516',
  'objects': [{'object_id': 1,
    'category': 'adult',
    'is_thing': True,
    'status': {'running': [[0, 219]], 'standing': [[220, 417]]}},
   {'object_id': 2,
    'category': 'child',
    'is_thing': True,
    'status': {'smiling': [[381, 417]]}},
   {'object_id': 3,
    'category': 'dog',
    'is_thing': True,
    'status': {'walking': [[173, 202]]}},
   {'object_id': 4, 'category': 'road', 'is_thing': True, 'status': []},
   {'object_id': 5, 'category': 'hat', 'is_thing': True, 'status': []},
   {'object_id': 6, 'category': 'bike', 'is_thing': True, 'status': []},
   {'object_id': 7,
    'category': 'adult',
    'is_thing': True,
    'status': {'running': [[100, 129]]}},
   {'object_id': 8, 'category': 'basket', 'is_thing': True, 'status': []},
   {'object_id': 9,
    'category': 'adult',
    'is_thing': True,
    'status': {'walking': [[195, 220]], 'standing': [[221, 255]]}}],
  'meta': {'no_frames': 418,
   'height': 480,
   'width': 640,
   'f

### Load QT

In [139]:
sample = load_pickle("/mnt/lustre/jkyang/wxpeng/CVPR23/PVSG_Image/work_dirs/test_default_ckpt4_tracking_and_save_qf2/0028_4021064662/query_feats.pickle")

In [140]:
sample

[QFT_30_(1_95),
 QFT_31_(1_69),
 QFT_32_(1_95),
 QFT_33_(1_95),
 QFT_34_(9_10),
 QFT_35_(47_47),
 QFT_36_(70_74),
 QFT_37_(76_95)]

In [141]:
sample[0].qf_tube

[{'query_feat': array([ 8.4782743e-01, -3.0031642e-01,  6.0156427e-02,  2.8273306e+00,
         -1.4651597e+00, -1.8568148e-01,  8.0950546e-01,  2.2707720e-01,
          4.4827732e-01, -8.3080018e-01,  2.4955420e-01, -1.2573630e+00,
          1.7589107e-01,  8.3755702e-01,  1.2977116e+00, -9.8435330e-01,
         -6.0543877e-01, -6.7724824e-01,  1.3147886e-01, -2.3643634e+00,
          3.8276840e-02,  1.2200440e+00,  4.2427206e-01, -9.4061792e-01,
         -3.6302623e-01,  2.1020418e-01, -4.0606651e-03,  3.3506477e-01,
         -1.5676373e+00, -1.2416058e+00, -1.3082772e+00, -1.7140206e+00,
          2.3251119e+00, -1.0968616e+00, -1.0134369e+00,  1.1753519e+00,
         -2.8808618e-01,  1.3678262e+00,  6.8966740e-01, -4.8803589e-01,
         -3.2231843e-01, -9.1194820e-01,  3.7971759e-01,  1.6083194e-01,
         -1.5597373e+00,  2.3955584e-01,  1.1459029e+00, -1.3499429e+00,
          4.4050193e-01,  8.7653178e-01, -1.5912364e+00,  8.5000694e-02,
         -1.2988703e+00,  3.1757402e-

### Load Tracked Masks from txt

In [142]:
import pycocotools.mask as mask_utils
import numpy as np
from itertools import groupby

In [143]:
labels = []
results = []
label_path = "/mnt/lustre/jkyang/wxpeng/CVPR23/PVSG_Image/work_dirs/test_default_ckpt4_tracking_and_save_qf2/0028_4021064662/quantitive/masks.txt"
with open(label_path, 'r') as f:
    for line in f:
        labels.append(line.strip().split())

for label in labels:
    frame_id, track_id, _, h, w, m = label
    rle = {'size':(int(h),int(w)), 'counts':m}
    mask = mask_utils.decode(rle)
    results.append(dict(fid=frame_id, tid=track_id, mask=mask))

In [144]:
results

[{'fid': '1',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '1',
  'tid': '31',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '1',
  'tid': '32',
  'mask': array([[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '1',
  'tid': '33',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],


In [145]:
# define a function for key
def key_func(k):
    return k['tid']
 
# sort data by 'tid' key.
results = sorted(results, key=key_func)

# group by tid
masks_grp_by_tid = {}
for key, value in groupby(results, key_func):
    masks_grp_by_tid[key] = list(value)

In [146]:
masks_grp_by_tid['30'] # remember the start fid of unitrack is 1, but ours is 0!

[{'fid': '1',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '2',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '3',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '4',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],


### Load GT Masks

In [147]:
import os
from pathlib import Path
from PIL import Image
from collections import defaultdict
from tqdm import tqdm

In [148]:
def read_pan_mask_next_frame(mask_tubes, pan_mask, cur_len, h, w):
    cur_ids = list(mask_tubes.keys())
    new_ids = list(np.unique(pan_mask))
    all_ids = list(set(cur_ids + new_ids))
    # for no mask frame -- all zeros
    dummy_mask = np.zeros((h,w))

    for instance_id in all_ids:
        if instance_id == 0:
            continue
        if instance_id not in new_ids: # this frame has no this object
            mask_tubes[instance_id].append(dummy_mask)
            continue
        if instance_id not in cur_ids: # this object first show up
            mask_tubes[instance_id].extend([dummy_mask for i in range(cur_len)])
            
        mask_tubes[instance_id].append((pan_mask == instance_id).astype(int))
    return mask_tubes

gt_masks_root = Path("/mnt/lustre/jkyang/wxpeng/CVPR23/PVSG_Image/data/pvsg_demo/train/masks")
def get_gt_mask_tubes_one_video(vid):
    gt_masks_root_vid = gt_masks_root / vid
    gt_pan_mask_paths = [str(x) for x in sorted(gt_masks_root_vid.rglob("*.png"))]
    
    mask_tubes = defaultdict(list)
    cur_len = 0
    for mask_path in tqdm(gt_pan_mask_paths):
        pan_mask = np.array(Image.open(mask_path))
        h, w = pan_mask.shape
        mask_tubes = read_pan_mask_next_frame(mask_tubes, pan_mask, cur_len, h, w)
        cur_len += 1
    return mask_tubes


def check_has_none(mask_tube):
    return any(ele is None for ele in mask_tube)

In [149]:
mask_tubes_gt = get_gt_mask_tubes_one_video("0028_4021064662")

100%|███████████████████████████████████████████| 95/95 [00:01<00:00, 67.40it/s]


In [150]:
mask_tubes_gt

defaultdict(list,
            {1: [array([[0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     ...,
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0]]),
              array([[0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     ...,
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0]]),
              array([[0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     ...,
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0],
                     [0, 0, 0, ..., 0, 0, 0]]),
              array([[0, 0, 0, ..., 0, 0, 0],
                     

### Match GT & TM
sample: 0010_8610561401

#gt 
-- mask_tubes_gt

#predicted from mask2former + unitrack
-- masks_grp_by_tid

In [151]:
def binaryMaskIOU(mask1, mask2):   
    mask1_area = np.count_nonzero(mask1 == 1)
    mask2_area = np.count_nonzero(mask2 == 1)
    intersection = np.count_nonzero(np.logical_and(mask1==1, mask2==1))
    iou = intersection/(mask1_area+mask2_area-intersection)
    return iou

In [152]:
# gt 
gt_mask_tubes = mask_tubes_gt
# predicted from mask2former + unitrack
pred_mask_tubes = masks_grp_by_tid

In [153]:
gt_mask_tubes[1]

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
   

In [154]:
pred_mask_tubes['30']

[{'fid': '1',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '2',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '3',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)},
 {'fid': '4',
  'tid': '30',
  'mask': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],


In [155]:
# init gt mark for init which part of gt is assigned to which pred mask tube
# tids = list(pred_mask_tubes.keys())
# mark = np.array([-1 for i in range(gt_len)])
# gt_marks = {tid: np.array([-1 for i in range(len(pred_mask_tubes[tid]))]) for tid in tids}

# init iou score for all pred mask tube
assigned_labels = {tid: -1 for tid in pred_mask_tubes.keys()}
iou_scores = {tid: -1 for tid in pred_mask_tubes.keys()}

iou_thres = 0.85
for tid, pred_mask_tube in tqdm(pred_mask_tubes.items()): # iterare all pred mask tubes
    gt_id = -1 # pred mask tube只会对应一个gt tube，但是可能对应的是part of it
    iou_score = -np.inf
    dummy_tube = np.array([int(x['fid']) - 1 for x in pred_mask_tube])# to mark which part of pred has mask!
    # compute viou with all gt mask tubes
    for gt_instance_id, gt_mask_tube in gt_mask_tubes.items():
        viou = 0.0
        count = 0.0
        for pred_mask_dict in pred_mask_tube: # iterate every frame in a pred mask tube
            fid = int(pred_mask_dict['fid']) - 1 # our gt starts from 0, but pred starts from 1, so need - 1
            pred_mask = pred_mask_dict['mask']
            gt_mask = gt_mask_tube[fid]
            iou = binaryMaskIOU(pred_mask, gt_mask)
            viou += iou
            count += 1
        viou = viou / count
        if viou >= iou_thres and viou > iou_score:
            gt_id = gt_instance_id
            iou_score = viou
    if gt_id != -1: # has some > 0.85
        iou_scores[tid] = iou_score # remember this highest iou score for this pred mask tube
        assigned_labels[tid] = gt_id # remember which part of gt is assigned to a pred(tid) - 这条gt_tube的dummy_id的部分被assign给当前pred mask tube
            
        
        
        

100%|█████████████████████████████████████████████| 8/8 [00:01<00:00,  4.06it/s]


In [156]:
def match_gt_pred_mask_tubes(pred_mask_tubes, gt_mask_tubes):
    # init iou score for all pred mask tube
    assigned_labels = {tid: -1 for tid in pred_mask_tubes.keys()}
    iou_scores = {tid: -1 for tid in pred_mask_tubes.keys()}

    iou_thres = 0.85
    for tid, pred_mask_tube in tqdm(pred_mask_tubes.items()): # iterare all pred mask tubes
        gt_id = -1 # pred mask tube只会对应一个gt tube，但是可能对应的是part of it
        iou_score = -np.inf
        # compute viou with all gt mask tubes
        for gt_instance_id, gt_mask_tube in gt_mask_tubes.items():
            viou = 0.0
            count = 0.0
            for pred_mask_dict in pred_mask_tube: # iterate every frame in a pred mask tube
                fid = int(pred_mask_dict['fid']) - 1 # our gt starts from 0, but pred starts from 1, so need - 1
                pred_mask = pred_mask_dict['mask']
                gt_mask = gt_mask_tube[fid]
                iou = binaryMaskIOU(pred_mask, gt_mask)
                viou += iou
                count += 1
            viou = viou / count
            if viou >= iou_thres and viou > iou_score:
                gt_id = gt_instance_id
                iou_score = viou
        if gt_id != -1: # has some > 0.85
            iou_scores[tid] = iou_score # remember this highest iou score for this pred mask tube
            assigned_labels[tid] = gt_id # remember which part of gt is assigned to a pred(tid) - 这条gt_tube的dummy_id的部分被assign给当前pred mask tube

    return assigned_labels, iou_scores
        
        

In [157]:
iou_scores

{'30': -1,
 '31': 0.8820971996459773,
 '32': 0.9918819272801364,
 '33': 0.9266905901121045,
 '34': -1,
 '35': -1,
 '36': -1,
 '37': 0.9035075231421901}

In [158]:
assigned_labels

{'30': -1, '31': 2, '32': 4, '33': 1, '34': -1, '35': -1, '36': -1, '37': 2}

### Match Feature Tube and GT Relation

In [159]:
THING_CLASSES = ['lighter', 'stand', 'flower', 'glass', 'book', 'spoon', 'glasses', 
                 'microphone', 'scissor', 'towel', 'basket', 'adult', 'child', 'baby', 
                 'horse', 'cat', 'dog', 'bed', 'sink', 'faucet', 'sofa', 'table', 'chair', 
                 'light', 'knife', 'fork', 'candle', 'plate', 'bowl', 'bottle', 'cup', 
                 'rock', 'road', 'grass', 'hat', 'vegetable', 'fruit', 'cake', 'bread', 
                 'paper', 'bag', 'box', 'cellphone', 'camera', 'ballon', 'toy', 'racket', 
                 'bat', 'ball', 'fountain', 'bench', 'bike', 'car']
STUFF_CLASSES = ['fence', 'tree', 'ground', 'pavement', 'floor', 'ceiling', 'wall', 'water']
BACKGROUND_CLASSES = ['background'] # none segmenation part 'void'
CLASSES = THING_CLASSES + STUFF_CLASSES + BACKGROUND_CLASSES

Now we have assigned_labels, sample (feature tubes from mask2former + unitrack), and gt_relations

In [160]:
assigned_labels

{'30': -1, '31': 2, '32': 4, '33': 1, '34': -1, '35': -1, '36': -1, '37': 2}

In [161]:
gt_ids_keep = list(set([v for v in assigned_labels.values() if v != -1]))
gt_ids_keep

[1, 2, 4]

In [162]:
sample # remember sample fid starts from 1 !

[QFT_30_(1_95),
 QFT_31_(1_69),
 QFT_32_(1_95),
 QFT_33_(1_95),
 QFT_34_(9_10),
 QFT_35_(47_47),
 QFT_36_(70_74),
 QFT_37_(76_95)]

In [168]:
gt["0028_4021064662"]['relations'] # remember gt relation fid starts from 0 !

[[3, 4, 'on', [[0, 94]]],
 [3, 2, 'in front of', [[0, 94]]],
 [3, 1, 'in front of', [[0, 94]]],
 [1, 4, 'standing on', [[0, 94]]],
 [2, 4, 'sitting on', [[0, 5]]],
 [2, 5, 'passing over', [[16, 20]]],
 [2, 4, 'standing on', [[11, 35], [91, 94]]],
 [2, 4, 'running on', [[35, 49]]],
 [2, 1, 'in front of', [[38, 39]]],
 [1, 5, 'throwing', [[48, 50]]],
 [2, 5, 'catching', [[49, 56]]],
 [2, 1, 'running to', [[56, 63]]],
 [1, 2, 'putting down', [[63, 83]]]]

In [169]:
gt_relation_filtered = [rel for rel in gt["0028_4021064662"]['relations'] if rel[0] in gt_ids_keep and rel[1] in gt_ids_keep]

In [170]:
gt_relation_filtered

[[1, 4, 'standing on', [[0, 94]]],
 [2, 4, 'sitting on', [[0, 5]]],
 [2, 4, 'standing on', [[11, 35], [91, 94]]],
 [2, 4, 'running on', [[35, 49]]],
 [2, 1, 'in front of', [[38, 39]]],
 [2, 1, 'running to', [[56, 63]]],
 [1, 2, 'putting down', [[63, 83]]]]

In [182]:
# get filtered qf_tube out
def filter_qf_tubes(assigned_labels, qf_tube_obj_list):
    # take out those have assigned labels in gt
    qf_tubes_filtered = []
    for (tid, gt_id), qf_tube_obj in zip(assigned_labels.items(), qf_tube_obj_list):
        if gt_id == -1:
            continue
        qf_tubes_filtered.append(dict(tid=int(tid),
                                      gt_id=gt_id,
                                      qf_tube=qf_tube_obj.qf_tube))
    return qf_tubes_filtered

def pair_qf_tubes(qf_tubes_filtered):
    # pair to get true/false tube to indicate which part should have a label (both have qf tubes)
    # avoid pairing with itself (same gt_id)
    pairs = []
    for s in qf_tubes_filtered:
        for o in qf_tubes_filtered:
            if (s['tid'] == o['tid']) or (s['gt_id'] == o['gt_id']):
                continue
            s_indicator = np.array([True if ele is not None else False for ele in s['qf_tube']])
            o_indicator = np.array([True if ele is not None else False for ele in o['qf_tube']])
            pair_indicator = s_indicator * o_indicator
            pairs.append(dict(so_tid=[s['tid'], o['tid']],
                              so_gt_id=[s['gt_id'], o['gt_id']],
                              indicator=pair_indicator))
    return pairs
    

def assign_relation_label(gt_relations, pairs):
    # assigne label (label list) to every qf_tube pair in pairs
    if len(pairs) == 0:
        return []
    labels = []
    num_frames = len(pairs[0]['indicator'])
    for pair in pairs:
        label_this_pair = [[] for i in range(num_frames)]
        s_gt_id, o_gt_id = pair['so_gt_id']
        indicator = pair['indicator']
        for gt_relation in gt_relations:
            if s_gt_id == gt_relation[0] and o_gt_id == gt_relation[1]:
                predicate = gt_relation[2]
                intervals = gt_relation[3]
                for interval in intervals: # one might have sevel time intervals for a relation
                    # remember our interval is not close on the right side but "range()" does! need + 1
                    start, end = interval[0], interval[1]
                    for i in range(start, end + 1):
                        if indicator[i]: # if also has a pair tube here
                            label_this_pair[i].append(predicate)
        labels.append(dict(so_tid=pair['so_tid'],
                           so_gt_id=pair['so_gt_id'],
                           label=label_this_pair))
    return labels
    
def get_labels_single_video(assigned_labels, qf_tube_obj_list, gt_relations):
    qf_tubes_filtered = filter_qf_tubes(assigned_labels, qf_tube_obj_list)
    pairs = pair_qf_tubes(qf_tubes_filtered)
    labels = assign_relation_label(gt_relations, pairs)
    return labels

In [174]:
pairs

[{'so_tid': [31, 32],
  'so_gt_id': [2, 4],
  'indicator': array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False])},
 {'so_tid': [31, 33],
  'so_gt_id': [2, 1],
  'indicator': array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  Tr

In [175]:
gt_relations = gt["0028_4021064662"]['relations']
gt_relations

[[3, 4, 'on', [[0, 94]]],
 [3, 2, 'in front of', [[0, 94]]],
 [3, 1, 'in front of', [[0, 94]]],
 [1, 4, 'standing on', [[0, 94]]],
 [2, 4, 'sitting on', [[0, 5]]],
 [2, 5, 'passing over', [[16, 20]]],
 [2, 4, 'standing on', [[11, 35], [91, 94]]],
 [2, 4, 'running on', [[35, 49]]],
 [2, 1, 'in front of', [[38, 39]]],
 [1, 5, 'throwing', [[48, 50]]],
 [2, 5, 'catching', [[49, 56]]],
 [2, 1, 'running to', [[56, 63]]],
 [1, 2, 'putting down', [[63, 83]]]]

In [183]:
labels

[{'so_tid': [31, 32],
  'so_gt_id': [2, 4],
  'label': [['sitting on'],
   ['sitting on'],
   ['sitting on'],
   ['sitting on'],
   ['sitting on'],
   ['sitting on'],
   [],
   [],
   [],
   [],
   [],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on'],
   ['standing on', 'running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   ['running on'],
   [],
   [],
   [

## Summarize codes

In [187]:
from pathlib import Path
import os

In [186]:
gt_mask_root=Path("/mnt/lustre/jkyang/wxpeng/CVPR23/PVSG_Image/data/pvsg_demo/train/masks")

In [188]:
os.listdir(gt_mask_root)

['1100_9117425466',
 '0057_7001078933',
 '0028_4021064662',
 '1007_6631583821',
 '1006_4580824633',
 '0010_8610561401',
 '1012_4024008346',
 '1000_6828150903',
 '1124_9861436503',
 '1015_4698622422',
 '0046_11919433184',
 '1001_7007447516',
 '1002_5280626374',
 '1021_4278168115',
 '1025_6244382586']

In [193]:
import sys
sys.path.append("/mnt/lustre/jkyang/wxpeng/CVPR23/")